<a href="https://colab.research.google.com/github/lelouch711/Projects/blob/Deep-learning/churn_rate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib as msn
import seaborn as sns
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
ds = pd.read_csv('/etc/Churn_Modelling.csv')
X = ds.iloc[:,3:-1].values
Y = ds.iloc[:,-1].values

In [ ]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [ ]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[1])],remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2,random_state = 0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [ ]:
import tensorflow as tf
ann = tf.keras.models.Sequential()

First Hidden Layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Second Hidden Layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Output Layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

Compiling

In [ ]:
ann.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics = ['accuracy'])

Training


In [ ]:
ann.fit(X_train, Y_train, batch_size = 32, epochs  = 100)

Epoch 1/100
250/250 [==============================] - 2s 3ms/step - loss: 0.6616 - accuracy: 0.6065
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4729 - accuracy: 0.8009
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4378 - accuracy: 0.8061
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4186 - accuracy: 0.8164
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4042 - accuracy: 0.8270
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3914 - accuracy: 0.8365
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3799 - accuracy: 0.8443
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3710 - accuracy: 0.8489
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3629 - accuracy: 0.8519
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3573 - accura

In [ ]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])))

1/1 [==============================] - 0s 118ms/step
[[0.04213958]]


In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))


63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test,y_pred)
print(cm)
accuracy_score(Y_test,y_pred)

[[1523   72]
 [ 212  193]]


0.858